"""Patch client MAP-EVIDENCE-V1: section preuve map dans le panneau LM de calib.html.

Crop yanis (cyan = xyz actuel), bouton "proposer retriangulation" (dry-run,
crosshair orange), verdicts map-valide/rejete/effacer ecrits live dans
gtamapdata/map_validated.json.

PREREQUIS: patch_mapev_server.py. Idempotent. Backup: .bak_mapev
"""
import shutil, sys

P = 'tools/calib.html'
s = open(P).read()
if 'MAP-EVIDENCE-V1' in s:
    print('deja patche'); sys.exit(0)
shutil.copy(P, P + '.bak_mapev')

old = '      <div class="lm-info-row" id="lm-info-others"></div>\n    </div>'
assert old in s, 'markup panneau LM introuvable'
s = s.replace(old, '      <div class="lm-info-row" id="lm-info-others"></div>\n' + '      <!-- [MAP-EVIDENCE-V1] preuve map: crop yanis + verdict -->\n      <div id="lm-map-ev" style="display:none;margin-top:8px">\n        <img id="lm-map-img" style="width:100%;border-radius:6px;border:1px solid var(--border);display:block" alt="map crop">\n        <div id="lm-map-delta" style="font-family:var(--mono);font-size:9.5px;color:var(--mid);margin-top:4px"></div>\n        <div style="display:flex;gap:5px;margin-top:6px;flex-wrap:wrap">\n          <button class="f-btn" id="lm-map-propose" style="font-size:10px">proposer retriangulation</button>\n          <button class="f-btn" id="lm-map-ok" style="font-size:10px;color:var(--green);border-color:var(--green)">✓ map-valide</button>\n          <button class="f-btn" id="lm-map-bad" style="font-size:10px;color:var(--red);border-color:var(--red)">✗ map-rejete</button>\n          <button class="f-btn" id="lm-map-clear" style="font-size:10px">effacer</button>\n          <span id="lm-map-verdict" style="font-family:var(--mono);font-size:10px;align-self:center;color:var(--mid)"></span>\n        </div>\n        <div style="font-family:var(--mono);font-size:9px;color:var(--dim);margin-top:4px">\n          cyan = xyz actuel · orange = proposition · la map n\'est pas du ground truth: valide = prior 5m, rejete = exclu du bundle</div>\n      </div>\n' + '    </div>', 1)

old = "    lmInfoPanel.classList.add('show');\n  } catch (e) {\n    console.error('lm_info failed:', e);\n    lmInfoPanel.classList.remove('show');\n  }\n}"
assert old in s, 'showLmInfo introuvable'
s = s.replace(old, "    lmInfoPanel.classList.add('show');\n    updateLmMapEvidence(lmName, info.has_xyz);  // [MAP-EVIDENCE-V1]\n  } catch (e) {\n    console.error('lm_info failed:', e);\n    lmInfoPanel.classList.remove('show');\n  }\n}\n\n// [MAP-EVIDENCE-V1] preuve map dans l'inspecteur de LM\nlet _mapEvLm = null;\nasync function updateLmMapEvidence(lmName, hasXyz) {\n  const box = document.getElementById('lm-map-ev');\n  _mapEvLm = lmName;\n  if (!hasXyz) { box.style.display = 'none'; return; }\n  box.style.display = 'block';\n  document.getElementById('lm-map-delta').textContent = '';\n  document.getElementById('lm-map-img').src = '/api/lm_map_crop?lm=' + encodeURIComponent(lmName) + '&t=' + Date.now();\n  const v = await fetch('/api/map_verdict?lm=' + encodeURIComponent(lmName)).then(r => r.json()).catch(() => ({}));\n  renderMapVerdict(v.verdict);\n}\nfunction renderMapVerdict(v) {\n  const el = document.getElementById('lm-map-verdict');\n  el.textContent = v === 'validated' ? '✓ valide (prior 5m)' : v === 'rejected' ? '✗ rejete (exclu bundle)' : '— sans verdict';\n  el.style.color = v === 'validated' ? 'var(--green)' : v === 'rejected' ? 'var(--red)' : 'var(--mid)';\n}\ndocument.getElementById('lm-map-propose').addEventListener('click', async () => {\n  if (!_mapEvLm) return;\n  const d = document.getElementById('lm-map-delta');\n  d.textContent = 'triangulation dry-run…';\n  const r = await fetch('/api/triangulate?lm=' + encodeURIComponent(_mapEvLm) + '&dry=1').then(x => x.json()).catch(() => null);\n  if (!r || !r.xyz) { d.textContent = 'pas triangulable (' + ((r && r.error) || 'sources insuffisantes') + ')'; return; }\n  document.getElementById('lm-map-img').src = '/api/lm_map_crop?lm=' + encodeURIComponent(_mapEvLm) +\n    '&x2=' + r.xyz[0] + '&y2=' + r.xyz[1] + '&t=' + Date.now();\n  const err = r.error_m != null ? r.error_m.toFixed(2) + 'm' : '?';\n  d.textContent = 'proposition (orange): err ' + err + ' · sources: ' + (r.source_cameras || r.sources || r.kept_sources || []).join(', ');\n});\ndocument.getElementById('lm-map-ok').addEventListener('click', async () => {\n  if (!_mapEvLm) return;\n  const v = await fetch('/api/map_verdict?lm=' + encodeURIComponent(_mapEvLm) + '&status=validated').then(r => r.json());\n  renderMapVerdict(v.verdict);\n});\ndocument.getElementById('lm-map-bad').addEventListener('click', async () => {\n  if (!_mapEvLm) return;\n  const v = await fetch('/api/map_verdict?lm=' + encodeURIComponent(_mapEvLm) + '&status=rejected').then(r => r.json());\n  renderMapVerdict(v.verdict);\n});\ndocument.getElementById('lm-map-clear').addEventListener('click', async () => {\n  if (!_mapEvLm) return;\n  const v = await fetch('/api/map_verdict?lm=' + encodeURIComponent(_mapEvLm) + '&status=clear').then(r => r.json());\n  renderMapVerdict(v.verdict);\n});", 1)
open(P, 'w').write(s)
print('client MAP-EVIDENCE-V1 patche. Backup: .bak_mapev')
