import gtamaplib as ml
import gtamapdata as md
from find_camera_optimizer import find_camera_with_refinement

find_camera_with_refinement(
    cam_name="Leonida Keys Postcard (X)",
    lm_names=[
        "Lake Surprise Viaduct (15B)", "Lake Surprise Viaduct (14B)",
        "Lake Surprise Viaduct (13B)", "Lake Surprise Viaduct (12B)",
        "Lake Surprise Viaduct (11B)", "Lake Surprise Viaduct (10B)",
        "Lake Surprise Viaduct (9B)", "Lake Surprise Viaduct (8B)",
        "Lake Surprise Viaduct (7B)", "Lake Surprise Viaduct (6B)",
        "Lake Surprise Viaduct (5B)", "Lake Surprise Viaduct (4B)",
        "Lake Surprise Viaduct (3B)", "Lake Surprise Viaduct (2B)",
        "Keys Bridge (1B)", "Keys Bridge (2B)", "Keys Bridge (3B)",
        "Keys Bridge (4B)", "Keys Bridge (5B)", "Keys Bridge (6B)",
        "Keys Bridge (7B)", "Keys Bridge (C)",
        "Turkey Point Nuclear Power Station (1)",
        "Turkey Point Nuclear Power Station (2)",
        "Turkey Point Nuclear Power Station (3)",
        "Key Lento (E)", "Key Lento (A)", "Key Lento (J)",
        "500 Pompano Dr", "200 Pompano Dr", "180 Pompano Dr",
        "Marina Club at Blackwater Sound (N)",
        "Marina Club at Blackwater Sound (S)",
        "102180 Overseas Hwy",
        "Island X (S)", "Island Z (S)", "Island Y (S)",
        "Island A (W)", "Island F (E)", "Island F (W)",
        "Island G (E)", "Island G (W)",
        "Island J (E)", "Island J (W)", "Tree on Island J",
        "House with Pier (E)", "Billboard #2 (Key Lento)",
        "Pin A02R", "Pin A03L", "Pin A03R", "Pin A04L", "Pin A04R",
        "Pin A05L", "Pin A05R", "Pin A06L", "Pin A06R",
        "Pin A07L", "Pin A07R", "Pin A08L", "Pin A08R",
        "Pin B01L", "Pin B01R", "Pin B02L", "Pin B02R",
        "Pin B03L", "Pin B03R", "Pin B04L", "Pin B04R",
        "Pin C01R", "Pin C02L", "Pin C02R",
        "Pin C03L", "Pin C03R", "Pin C04L", "Pin C04R",
        "Pin D01L", "Pin D01R", "Pin D02L", "Pin D02R",
    ],
    rays=[],
    line=((-3808.492, -6794.543), (-3808.492, -6794.543)),
    radius=10,
    step=1,
    z_limits=(130, 165),
    pitch_range=(-14.0, -9.0, 0.1),
    hfov_range=(44.0, 50.0, 0.25),
    map_name="yanis",
    map_scale=1.0,
    map_area=(-5000, -7500, -1000, -4500),
    projection_area=None,
    basename="renders/LeonidaKeysPostcard",
    refine=True
)
