#!/usr/bin/env python3
"""mesh_shift_solve.py — translation au sol d'un mesh mesuree par ses aretes laterales dans PLUSIEURS cams fiables. [MESH-SHIFT-V1 2026-10-06]

Entree: tools/generated/pose_audit.json (mesh_pose_audit.py). Cams 'fiables' = >= 8 volumes juges et decalage global
|shift| <= 1.5 px (leur pose est confirmee par les autres meshes -> pas de circularite cam <-> mesh). Pour chaque mesh:
centre_d (px a 1280, decalage du centre des aretes L/R de la frame par rapport au rendu) dans chaque cam fiable, moins
le decalage global de la cam; jacobien numerique d(x_pixel)/d(dx, dy) en projetant le centre du mesh a mi-hauteur;
moindres carres ponderes -> translation (dx, dy) en metres, residus avant/apres. Une seule direction de vue = une
seule composante observable (signalee). Rien n'est ecrit dans les meshes: rapport seulement (docs/mesh_shift_report.md).
Usage: python3 tools/mesh_shift_solve.py [--min-cams 3]
"""
import json, os, sys, math
import numpy as np

THIS = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.dirname(THIS); sys.path.insert(0, THIS); sys.path.insert(0, REPO)
import common
import mesh_solids as MS
from mesh_pose_audit import basis, WORK

AUD = os.path.join(THIS, 'generated', 'pose_audit.json')
OUT = os.path.join(REPO, 'docs', 'mesh_shift_report.md')


def main():
    mn = int(sys.argv[sys.argv.index('--min-cams') + 1]) if '--min-cams' in sys.argv else 3
    A = json.load(open(AUD)); S = MS.build()
    good = {c: o for c, o in A.items() if o['n_judged'] >= 8 and o['fit'] and abs(o['fit']['shift_px']) <= 1.5}
    obs = {}
    for cam, o in good.items():
        for n, m in o['meshes'].items():
            if 'center_d' in m: obs.setdefault(n, []).append((cam, m['center_d'] - o['fit']['shift_px'], m['width_d']))
    rows = []
    for n, L in obs.items():
        if len(L) < mn or n not in S: continue
        so = S[n]; P = np.array([q for Ly in so['layers'] for p in Ly['polys'] for q in p['outer']], float)
        c3 = np.array([*P.mean(0), (so['layers'][0]['z0'] + so['layers'][-1]['z1']) / 2])
        J, b, wt, dirs = [], [], [], []
        for cam, d, wd in L:
            cm = common.get_cam(cam); B = basis(cm); s = WORK / B[5]
            def px(X):
                D = X - B[0]; return (B[5] / 2 + B[4] * (D @ B[2]) / (D @ B[1])) * s
            x0 = px(c3); J.append([px(c3 + [1, 0, 0]) - x0, px(c3 + [0, 1, 0]) - x0]); b.append(d); wt.append(1.0)
            dirs.append(math.degrees(math.atan2(*(c3[:2] - B[0][:2]))))
        J, b = np.array(J), np.array(b)
        sol, *_ = np.linalg.lstsq(J, b, rcond=None)
        sv = np.linalg.svd(J, compute_uv=False); cond = sv[0] / max(sv[-1], 1e-9)
        r0 = float(np.sqrt(np.mean(b ** 2))); r1 = float(np.sqrt(np.mean((b - J @ sol) ** 2)))
        spread = float(np.ptp(dirs)) if len(dirs) > 1 else 0.0
        rows.append((n, len(L), sol, r0, r1, cond, spread, float(np.median([w for _, _, w in L])), [c for c, _, _ in L]))
    rows.sort(key=lambda t: -(t[3] - t[4]))
    out = ['# Mesh ground shifts measured from several reliable cameras', '',
           'Generated by `tools/mesh_shift_solve.py` from `tools/generated/pose_audit.json`. Reliable cameras: >= 8 judged buildings and',
           'global edge shift <= 1.5 px (their pose is confirmed by the other meshes). For each mesh, the centre error of its left/right',
           'silhouette edges in each reliable camera is fitted as a ground translation (dx east, dy north, metres).',
           'Residuals in px at 1280 width. View spread < 25 deg = only one component is really observed. Report only: nothing applied.', '',
           '| building | cams | dx m | dy m | |shift| m | residual before px | after px | view spread deg | median width error px | cams |',
           '|---|---|---|---|---|---|---|---|---|---|']
    for n, k, sol, r0, r1, cond, spread, wmed, cams in rows:
        out.append('| %s | %d | %+.1f | %+.1f | %.1f | %.1f | %.1f | %.0f | %+.1f | %s |' % (n, k, sol[0], sol[1], float(np.hypot(*sol)), r0, r1, spread, wmed, '; '.join(cams[:6])))
        print('%-36s cams %2d  shift (%+6.1f, %+6.1f) m  |%.1f|  rms %.1f -> %.1f px  spread %3.0f deg  width %+.1f' % (n[:36], k, sol[0], sol[1], np.hypot(*sol), r0, r1, spread, wmed))
    open(OUT, 'w').write('\n'.join(out) + '\n'); print('->', OUT, '| cams fiables:', len(good))


if __name__ == '__main__':
    main()
