#!/usr/bin/env python3
"""mesh_click_list.py — liste des emprises V16 NON modelisees les plus visibles, pour une session de clics guidee. [CLICK-LIST-V1 2026-10-05]

Pourquoi des clics: les hauteurs automatiques par silhouette ont ete refutees (~41/44 faux a l'oeil) et l'appariement
automatique jeu -> batiment IRL (OSM) est trop imprecis (erreur LOO mediane 277 m au centre-ville, ~1 km a Vice Beach:
Vice City n'est pas une deformation lisse de Miami). Un mesh fidele = coins de toit cliques (landmarks) -> gen_footprint_mesh.

Classement: emprises du remplissage urbain (> 600 m2), visibles (centre a l'image, < 1500 m, rayon central non coupe par
un volume deja modelise) dans le plus de SCENES independantes (frames d'une meme video / serie (A)(B) comptees une fois).
Sortie: docs/mesh_click_list.md (anglais, public) — nom propose, position, aire, meilleures cams ou cliquer.
Usage: python3 tools/mesh_click_list.py [--top 40] [--bbox X0 Y0 X1 Y1 --name vicebeach]
"""
import json, os, sys, math, re
import numpy as np

THIS = os.path.dirname(os.path.abspath(__file__)); REPO = os.path.dirname(THIS); sys.path.insert(0, THIS); sys.path.insert(0, REPO)
import common
import mesh_solids as MSO
from facade_colors import basis, CAMS

MASS = os.path.join(THIS, 'threejs', '_v16_massing.json')
OUT = os.path.join(REPO, 'docs', 'mesh_click_list.md')


def scene(cam):
    k = re.sub(r'\s*\((?:[A-Z]|\d+|[NSEW]|Extended Look|X)\)\s*$', '', cam)
    k = re.sub(r'\s*v\d{3,4}\b.*$', '', k); k = re.sub(r'\s*f\d{2,3}\b.*$', '', k); k = re.sub(r'\s*\d+\s*$', '', k)
    return k.strip().lower()


def seg_hits_box(o, p, boxes):
    """le segment o->p (xy) traverse-t-il une boite englobante de volume modelise plus haut que la ligne de visee?"""
    for (x0, y0, x1, y1, zt) in boxes:
        d = p[:2] - o[:2]; t0, t1 = 0.0, 0.97
        for a, lo, hi in ((0, x0, x1), (1, y0, y1)):
            if abs(d[a]) < 1e-9:
                if not (lo <= o[a] <= hi): break
                continue
            ta, tb = (lo - o[a]) / d[a], (hi - o[a]) / d[a]
            t0, t1 = max(t0, min(ta, tb)), min(t1, max(ta, tb))
        else:
            if t0 < t1 and o[2] + (p[2] - o[2]) * t0 < zt: return True
    return False


def main():
    top = int(sys.argv[sys.argv.index('--top') + 1]) if '--top' in sys.argv else 40
    bb = [float(v) for v in sys.argv[sys.argv.index('--bbox') + 1:sys.argv.index('--bbox') + 5]] if '--bbox' in sys.argv else None
    out = OUT if '--name' not in sys.argv else OUT.replace('.md', '_%s.md' % sys.argv[sys.argv.index('--name') + 1])
    M = json.load(open(MASS)); C = json.load(open(CAMS))
    area = lambda O: abs(np.sum(O[:, 0] * np.roll(O[:, 1], 1) - np.roll(O[:, 0], 1) * O[:, 1])) / 2
    cand = [(i, np.array(m['o'], float), float(m['z'])) for i, m in enumerate(M) if area(np.array(m['o'], float)) > 600]
    if bb: cand = [c for c in cand if bb[0] <= c[1][:, 0].mean() <= bb[2] and bb[1] <= c[1][:, 1].mean() <= bb[3]]
    boxes = []
    for so in MSO.build().values():
        if not so['layers']: continue
        P = np.array([q for L in so['layers'] for p in L['polys'] for q in p['outer']])
        boxes.append((P[:, 0].min(), P[:, 1].min(), P[:, 0].max(), P[:, 1].max(), max(L['z1'] for L in so['layers'])))
    vis = {i: {} for i, _, _ in cand}
    for cam, c in C.items():
        if c.get('constraint_class') == 'X_excluded' or not os.path.exists(os.path.join(REPO, 'frames', cam + '.png')): continue
        try:
            o, f, r, u, fpx, W, H = basis(common.get_cam(cam), {'fov': c['fov']})
        except Exception: continue
        if fpx is None: continue
        for i, O, z0 in cand:
            cen = np.array([*O.mean(0), z0 + 8.0]); D = cen - o; z = D @ f; d = np.linalg.norm(D[:2])
            if z < 20 or d > 1500: continue
            x = W / 2 + fpx * (D @ r) / z; y = H / 2 - fpx * (D @ u) / z
            if not (0.05 * W < x < 0.95 * W and 0.05 * H < y < 0.95 * H): continue
            if seg_hits_box(o, cen, boxes): continue
            sc_ = scene(cam); px = fpx * math.sqrt(area(O)) / max(z, 1.0)          # taille apparente (px)
            if px > vis[i].get(sc_, ('', 0))[1]: vis[i][sc_] = (cam, px)
    rows = []
    for i, O, z0 in cand:
        v = vis[i]
        if len(v) < 2: continue
        best = sorted(v.values(), key=lambda t: -t[1])[:4]
        rows.append((len(v), i, O.mean(0), area(O), best))
    rows.sort(key=lambda t: (-t[0], -t[3]))
    L = ['# Unmodelled V16 buildings to click (most visible first)', '',
         'Generated by `tools/mesh_click_list.py`. For each building: click the roof corners in at least 2 of the listed cams',
         '(landmarks named `V16 #<id> (NE)`, `(NW)`, ...), then `tools/gen_footprint_mesh.py "V16 #<id>"` builds the measured mesh',
         'on the V16 footprint. Automatic heights were rejected (silhouette scan ~41/44 false; OSM matching error ~277 m).', '',
         '| # | V16 id | position (x, y) | footprint m² | independent scenes | best cams to click |', '|---|---|---|---|---|---|']
    for k, (n, i, c, a, best) in enumerate(rows[:top], 1):
        L.append('| %d | V16 #%d | %.0f, %.0f | %.0f | %d | %s |' % (k, i, c[0], c[1], a, n, '; '.join('%s (%.0f px)' % (b[0], b[1]) for b in best)))
    open(out, 'w').write('\n'.join(L) + '\n')
    print('%d emprises visibles dans >= 2 scenes; top %d -> %s' % (len(rows), top, out))


if __name__ == '__main__':
    main()
